export const AUTH_ERROR_CODES = {
  INVALID_ACCESS_TOKEN: 'GUITA-AUTH-001',
  INVALID_REFRESH_TOKEN: 'GUITA-AUTH-002',
  INVALID_SESSION: 'GUITA-AUTH-003',
  HOST_NOT_FOUND: 'GUITA-AUTH-004',
  IDENTITY_CONFLICT: 'GUITA-AUTH-005',
  USER_ID_GENERATION_FAILED: 'GUITA-AUTH-006',
  USER_NOT_FOUND: 'GUITA-AUTH-007',
} as const

export const AUTH_EVENT_NAMES = {
  LOGIN: 'guita.auth.login',
  LOGOUT: 'guita.auth.logout',
} as const

export const SESSION_REDIS_KEY_PREFIX = 'session:'
